import React, { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

const MusicPlayback = ({ accessToken }) => {
  const [currentTrack, setCurrentTrack] = useState(null);
  const [queue, setQueue] = useState([]);
  const [playlistName, setPlaylistName] = useState("My AI Mood Mix");
  const [saving, setSaving] = useState(false);

  // ---- Fetch currently playing track ----
  const fetchCurrentlyPlaying = async () => {
    try {
      const res = await fetch(
        "https://api.spotify.com/v1/me/player/currently-playing",
        {
          headers: { Authorization: `Bearer ${accessToken}` },
        }
      );
      if (res.status === 204) return; // nothing playing
      const data = await res.json();
      setCurrentTrack(data.item);
    } catch (err) {
      console.error("Error fetching current track:", err);
    }
  };

  // ---- Fetch queue ----
  const fetchQueue = async () => {
    try {
      const res = await fetch("https://api.spotify.com/v1/me/player/queue", {
        headers: { Authorization: `Bearer ${accessToken}` },
      });
      const data = await res.json();
      setQueue(data.queue || []);
    } catch (err) {
      console.error("Error fetching queue:", err);
    }
  };

  // ---- Save current playlist to Spotify ----
  const savePlaylist = async () => {
    if (!currentTrack && queue.length === 0) return;
    setSaving(true);
    try {
      // Get user ID
      const userRes = await fetch("https://api.spotify.com/v1/me", {
        headers: { Authorization: `Bearer ${accessToken}` },
      });
      const user = await userRes.json();

      // Create new playlist
      const playlistRes = await fetch(
        `https://api.spotify.com/v1/users/${user.id}/playlists`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${accessToken}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            name: playlistName,
            description: "Generated by Emotion-based Music Recommender",
            public: true,
          }),
        }
      );
      const playlist = await playlistRes.json();

      // Add current + queued songs
      const trackUris = [currentTrack?.uri, ...queue.map((t) => t.uri)].filter(
        Boolean
      );

      await fetch(
        `https://api.spotify.com/v1/playlists/${playlist.id}/tracks`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${accessToken}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ uris: trackUris }),
        }
      );

      alert(`Playlist "${playlistName}" saved to your Spotify!`);
    } catch (err) {
      console.error("Error saving playlist:", err);
      alert("Could not save playlist.");
    } finally {
      setSaving(false);
    }
  };

  // ---- Load data periodically ----
  useEffect(() => {
    fetchCurrentlyPlaying();
    fetchQueue();
    const interval = setInterval(() => {
      fetchCurrentlyPlaying();
      fetchQueue();
    }, 15000); // refresh every 15s
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-gradient-to-br from-green-500 via-blue-500 to-purple-500 text-white p-6">
      <div className="max-w-3xl w-full bg-white/10 rounded-2xl shadow-xl p-8">
        <h1 className="text-3xl font-bold text-center mb-6">🎧 Now Playing</h1>

        {currentTrack ? (
          <Card className="bg-white/20 text-white p-4 mb-8">
            <CardContent className="flex items-center space-x-4">
              <img
                src={currentTrack.album.images[0]?.url}
                alt={currentTrack.name}
                className="w-20 h-20 rounded-xl shadow-md"
              />
              <div>
                <h2 className="text-xl font-semibold">{currentTrack.name}</h2>
                <p className="text-gray-200">
                  {currentTrack.artists.map((a) => a.name).join(", ")}
                </p>
                <p className="text-sm mt-1 text-gray-300">
                  {currentTrack.album.name}
                </p>
              </div>
            </CardContent>
          </Card>
        ) : (
          <p className="text-center text-gray-200 mb-8">
            No song currently playing.
          </p>
        )}

        <h2 className="text-2xl font-semibold mb-4">⏭️ Up Next</h2>
        <div className="space-y-3 max-h-60 overflow-y-auto mb-6">
          {queue.length > 0 ? (
            queue.map((track, i) => (
              <div
                key={i}
                className="flex items-center bg-white/10 p-3 rounded-lg"
              >
                <img
                  src={track.album.images[0]?.url}
                  alt={track.name}
                  className="w-12 h-12 rounded-md mr-3"
                />
                <div>
                  <p className="font-medium">{track.name}</p>
                  <p className="text-sm text-gray-300">
                    {track.artists.map((a) => a.name).join(", ")}
                  </p>
                </div>
              </div>
            ))
          ) : (
            <p className="text-gray-200">No tracks in queue.</p>
          )}
        </div>

        <div className="flex flex-col sm:flex-row justify-center gap-3 items-center">
          <input
            type="text"
            value={playlistName}
            onChange={(e) => setPlaylistName(e.target.value)}
            className="rounded-full px-4 py-2 text-black w-full sm:w-auto"
            placeholder="Playlist name"
          />
          <Button
            onClick={savePlaylist}
            disabled={saving}
            className={`px-6 py-2 text-lg rounded-full font-semibold ${
              saving
                ? "bg-gray-400 cursor-wait"
                : "bg-green-500 hover:bg-green-600"
            }`}
          >
            {saving ? "Saving..." : "💾 Save Playlist"}
          </Button>
        </div>
      </div>
    </div>
  );
};

export default MusicPlayback;
